juxt/bidi

src/bidi/ring.clj

When a resource isn't found, the existing functionality just returns a response map in place of a handler, which then returns nil when passed a request. 
This PR ensures that the `:handler` key is always a valid handler, regardless of whether the resource is found.
James

Making 'Resources' return a handler when the resource isn't found, not a response

---

.travis.yml

sets up a `.travis.yml` so tests run on travis-ci. You'll have to turn it on via the webapp (https://travis-ci.org/profile/juxt) to make tests run (as I understand travis anyway)

add to travis ci

---

README.md

Removed deprecated from TaggedMatch in README and attributed it to Indentifiable Handler. Fixed a typo

Removed deprecated from TaggedMatch in README

---

src/bidi/bidi.cljx
test/bidi/bidi_test.cljx

This patch addresses issue #57 and allows routes that contain regular expressions (as per the README) to be used within 'compile-route'.

(#57) Support regexes in compile-route

---

src/bidi/bidi.cljx

The catch-all for extending protocols in ClojureScript is `default`, cf. https://github.com/clojure/clojurescript/blob/master/src/cljs/cljs/core.cljs#L882.

Fix cljs route compiling default case

---

bench/bidi/perf_test.clj
project.clj

Measuring benchmark results with `time` is **terribly confusing** on the JVM. I downloaded this project and ran the perf tests, and managed to get *wildly* differing results upon each run. Criterium (or something of its ilk) should be used instead, for more repeatable results.
Secondly, this project was running "benchmarks" with leiningen's default JVM options, which are optimized for startup time (see https://github.com/technomancy/leiningen/wiki/Faster), not performance. This PR creates a new profile `bench`, which replaces the default `lein` jvm options with reasonably optimized ones.
Criterium results from running on my machine:
```
lein test bidi.perf-test
Time to match using Compojure's routes
WARNING: Final GC required 1.520699241780737 % of runtime
Evaluation count : 14886480 in …
```

rewrite performance 'tests' to use criterium

---

README.md

This bit me while trying out yada; route-seq isn't a thing in the version claimed in the README.
(I'm fairly new to Clojure; is there a reason not to use Clojars' badges?)

Update current version in README

---

src/bidi/router.cljs

Hi Malcolm,
Have had a first bash at writing a CLJS router for Bidi - taking in a Bidi route structure and using Closure's 'History' to set and react to changes in the hash-fragment part of the URL.
Example usage:
```clojure
(require '[bidi.router :as br])
(let [!location (atom nil)
router (br/start-router! ["" {"/" ::home-page
"/page2" ::page2}]
{:on-navigate (fn [location]
(reset! !location location))
:default-location {:handler ::home-page}})]
...
(br/set-location! router {:handler ::page2}))
```
What do you think? More than happy to release this as a separate library if you don't think it belongs in Bidi core :)
We're getting an awful lot of use out of Bidi, btw - really appreciating having routes-as-data :)
Cheers,
James

First bash: Adding a CLJS 'router' that sets and reacts to changes in the hash fragment

---

src/bidi/ring.clj
test/bidi/ring_test.clj

When using vars for you handlers instead of fns / lambdas you can reload that handler function (and reload-the page) instead of doing a full (reset) to observe your changes.

Added support for using vars as handlers

---

src/bidi/bidi.cljx

I saw this issue while profiling a real application. So its not artificial.

Add Type Hints to Prevent Reflection Use

---

test/bidi/bidi_test.cljx

Context and RouteTarget were removed in e7c41e7.

Remove failing Context and RouteTarget tests

---

project.clj
src/bidi/schema.cljx

Change uses of `either` (deprecated) to use `cond-pre`, which is Schema
1.0.1's replacement. `either` no longer works, and throws a
`StackOverflow` exception.

Upgrade to Schema 1.0.1

---

project.clj
test/bidi/bidi_test.cljc
test/bidi/runner.cljs
test/bidi/schema_test.cljc

`clojurescript.test` has been deprecated in favour of `cljs.test`, the
testing library that ships with ClojureScript. In place of the test
runner provided by `clojurescript.test`, we use `doo`.

Switch from clojurescript.test to cljs.test

---

src/bidi/bidi.cljc
test/bidi/bidi_test.cljc

This adds the `Integer` implementation to the `ParameterEncoding` protocol.
`path-for` did not support `Integer` types, which is confusing because it's often hard to tell if you're passing in a `Long` or `Integer` (especially if the numeric came from a library that you do not control, e.g. an integer DB column from [yesql](https://github.com/krisajenkins/yesql)).
Here is a failing case:
```clojure
(def test-route ["" {["/" :id] :id-handler}])
(bidi/path-for test-route :id-handler :id 123)
; "/123"
(bidi/path-for test-route :id-handler :id (int 123))
;; java.lang.IllegalArgumentException: No implementation of method: :encode-parameter of protocol: #'bidi.bidi/ParameterEncoding found for class: java.lang.Integer
```

Integer support for `path-for`

---

README.md

The version number was outdated, using Clojars prevents any cat & mouse with remembering where to update version numbers.

Add version badge 

---

src/bidi/bidi.cljc
test/bidi/bidi_test.cljc

java.lang.Number is the superclass of Byte, Short, Integer and Long, which are all matched by PatternSegment. This generalizes https://github.com/juxt/bidi/pull/96.
Please test for cljs.

Add Number support to ParameterEncoding

---

src/bidi/bidi.cljc
test/bidi/bidi_test.cljc

Uses core-ish the URI libraries to match against just the path from a
given URI (and excludes query params!)
Also adds a test for this case.
See: https://github.com/juxt/bidi/issues/88 and https://github.com/juxt/bidi/issues/51

Ignore query parameters in a url when matching.

---

src/bidi/schema.cljc
test/bidi/schema_test.cljc

Hi ---
This pull request just updates the schema to include ':patch' in the MethodGuard enum.  While doing that, noticed that the 'Matched' schema tended to short-circuit at (s/=> s/Any s/Any) as maps are treated as callables, and was thus too permissive --- fixed by reordering the terms in the s/pre-cond expression.  Added a test case for this situation.
Haven't got phantomjs running on my dev box at the moment (problem during installation I haven't figured out), so haven't run the clojurescript tests, but the clojure ones are passing.
best,
Duncan

Add support for PATCH method

---

project.clj

Removes Phatomjs as a global dependency for running the tests for this project.
This should make the project way friendlier to beginners wanting to contribute (without fiddling around with phantomjs versions & installations).
I just did this as part of my PR here: https://github.com/weavejester/meta-merge/pull/7 and it definitely makes testing easier.

Switch to Rhino as Clojurescript Test Runner, removing global dependency

---

circle.yml

TravisCI unfortunately runs an old version of Leiningen (https://github.com/travis-ci/travis-ci/issues/5025) which means that .cljc tests are not run on the jvm, see this build: https://travis-ci.org/juxt/bidi/builds/98033023
> Ran 6 tests containing 34 assertions.
I've just tried circleci on my fork, and you can see in the test section that all is functional once more: https://circleci.com/gh/SevereOverfl0w/bidi/5
All tests are run in both areas. Success!
---
I have not removed `travis.yml` in this commit (but can). There is no reason not to have both enabled and choose a favourite at a later time. Also, the circle.yml file is not necessary, when enabling circleci for this repo, you can go into the project settings and just enter `lein test` as the test command, it defaults to `lein …

Enable CircleCI

---

README.md
test/bidi/bidi_test.cljc

Whilst playing with #106 I noticed that the README has incorrect usage of alts, this corrects it and adds a unit test for the use-case also.

Correct usage of alts in README, add corresponding test.

---

README.md

A nil from schema/check means a route is valid not invalid.
https://github.com/Prismatic/schema/blob/master/src/cljx/schema/core.cljx#L137

Fix schema/check documentation in README

---

src/bidi/schema.cljc

This improves slightly the error messages given when schema-checking fails.
Right now we have : ` (schema/check bidi.schema/RoutePair []) ;; [(not (present? "")) (not (present? ""))] `

Name the RoutePair schemas

---

src/bidi/bidi.cljc
test/bidi/bidi_test.cljc

Paths with chunks starting with colons — /like/::this/:one — are valid
but they were not parsed correctly by bidi. The reason was an exception
thrown by the java.net.URI constructor invoked in bidi/just-path.
java.net.URI assumed that a string like ":a" was missing a required URI
schema and threw.  Similar issues occurred in the ClojureScript edition.
This patch solves the problem by prefixing the path with an explicit
schema file:/// before invoking the constructor. Afterwards it drops
the slash which got prepended.
Interestingly enough, replacing bidi/just-path with the following
implementation solves the problem too and according to the test suite
it doesn't appear to be introducing any regressions. This being said,
my gut feeling tells me it might bite us in the future.
(defn …

Allow path chunks to start with a colon

---

src/bidi/ring.clj

`wrap-content` was being called inside the handler, rather than wraping it.

Fix `->Resources`

---

src/bidi/vhosts.clj

The new behavior is to turn the URL into a URI before recursing. This appears to be the intended behavior.

Avoid infinite loop when using URL in vhosts-model

---

README.md

Some indentation was off in the examples, so I made a quick fix

Indentation fixes for improved readability

---

src/bidi/bidi.cljc

Aleph request maps are of type aleph.http.core.NettyRequest, which
are lazy derived-maps (implemented in potemkin). Merging two
NettyRequests causes the :server-name key in the request map to be
resolved causing a getHostName lookup, which can block the request
for several seconds.

Fix merging of NettyRequest (aleph) envs

---

src/bidi/bidi.cljc
test/bidi/bidi_test.cljc

This allows vars to be matched in both Clojure and Clojurescript. Tests added as well.

Added support for cljs.core/Var

---

src/bidi/bidi.cljc
test/bidi/bidi_test.cljc

This fixes an invalid URI message when urls contains symbols which are
valid in URLs, but not in a URI, e.g. `<`. Also adds a regression test
for that.

Allow more chars in URLs

---

project.clj

Including bidi as a dependency can break handlers that are expecting a higher version of ring-core: ptaoussanis/sente#322
Resolves issue: #182 Bidi brings older version of `ring-core` into projects; should it be :scope "provided"?

ring provided instead of included as depencency

---

src/bidi/bidi.cljc

This PR fixes #189 removing an arity warning emited by shadow-cljs. 1LOC change. All tests are passing.

[FIX] #189 Shadow-cljs warinng on cljs.core.UUID constructor arity

---

.travis.yml
src/bidi/bidi.cljc

This provides a close cousin of `match-route*` to avoid forcing library consumers to use `unmatch-pair` which is less legible in calling code.

bidi: provide path-for*, let path-for depend on it

---

src/bidi/bidi.cljc
test/bidi/bidi_test.cljc

Accept UUIDs the same way Java does
Some UUID parameters are not matched, most noticeably the "nil" UUID consisting of only zeros. In addition, both Java (and e.g. .NET) and ClojureScript core accept a lot wider variety of "UUIDs", some of which are technically not correct.
This commit proposes to bring the bidi implementation in line with what Java accepts, which is any string with 5 parts separated by hyphens, which each part of a specific length and only hex characters.
Fixes #159

accept all uuids which Java and JavaScript will accept

---

src/bidi/vhosts.clj

uri-info requires a full req object or else it will NPE.  This isn't
required for just calculating a path.

Calculate path-for without using uri-info
